---
title: Data Visualization
author: Bill
date: '2017-09-25'
slug: data-visualization
categories:
  - dplyr
  - ggiraph
  - ggplot
tags:
  - data sceince
---

Today we are going to go over some basic data visualization techniques using the Lahman dataset, dplyr, ggplot2, and ggiraph.  Our goal will be to create a scatter plot that shows elite homerun hitters (that we will define as >= 400 career homeruns) and a comparison of there strikeouts.

First, we must filter and summarize hitters that were able to hit 400 homeruns in their careers.

This gives us a list of players who were able to hit 400 or more homeruns.  Notice that we named this table "df" so that we can easily refer to it throughout.

Next, we will join multiple tables together to make it easier to identify players.  We will do this with the "inner_join" command.

We have named our new table HR_vs_SO.

Using ggplot and ggiraph now, we will graph the players homeruns and strikeouts.

Now, we have a nice graph that shows the relationship between the players and their homeruns and strikeouts.
